clean:
  classification: false
  combine_files: false
  correlation_metric: pearson
  input_max_correlation_threshold: 1.0
  onehot_encode_target: false
  percentage_zeros_threshold: 1.0
  target: cnc_milling
evaluate: null
featurize:
  add_rolling_features: false
  features: null
  remove_features: null
  rolling_window_size: 100
  target_min_correlation_threshold: 0.0
profile:
  dataset: cnc_milling
scale:
  input: minmax
  output: null
sequentialize:
  future_predict: false
  overlap: 0
  shuffle_samples: false
  target_size: 1
  window_size: 10
split:
  calibrate_split: 0.0
  shuffle_files: false
  train_split: 0.7
train:
  batch_size: 256
  early_stopping: true
  kernel_size: 3
  learning_method: bcnn
  n_epochs: 10
  patience: 3
  train: False
  n_step_out: 1
