clean:
  classification: false
  combine_files: true
  correlation_metric: pearson
  input_max_correlation_threshold: 1.0
  onehot_encode_target: false
  percentage_zeros_threshold: 1.0
  target: Spindle_Torque
evaluate:
  show_inputs: false
featurize:
  add_gradient: null
  add_maximum: null
  add_mean: null
  add_min_max_range: null
  add_minimum: null
  add_peak_frequency: null
  add_slope: null
  add_slope_cos: null
  add_slope_sin: null
  add_standard_deviation: null
  add_sum: null
  add_variance: null
  remove_features:
  - Axis_X_Real_Position
  - Axis_Y_Real_Position
  - Axis_Z_Real_Position
  rolling_window_size_max_min: 100
  rolling_window_size_mean: 100
  rolling_window_size_standard_deviation: 100
  rolling_window_size_sum: 100
  target_min_correlation_threshold: 0.0
  use_all_engineered_features_on_all_variables: true
  variables_to_include:
  - Axis_X_Real_Position
  - Axis_Y_Real_Position
  - Axis_Z_Real_Position
profile:
  dataset: automotive_pn40
scale:
  input: minmax
  output: null
sequentialize:
  future_predict: false
  overlap: 0
  shuffle_samples: false
  target_size: 1
  window_size: 10
split:
  calibrate_split: 0.0
  shuffle_files: false
  train_split: 0.5
train:
  batch_size: 256
  early_stopping: true
  kernel_size: 6
  learning_method: lstm
  n_epochs: 200
  patience: 100
