profile:
    # dataset: automotive
    dataset: cnc_milling

clean:
    target: X1_ActualPosition
    # target: Spindle_Torque
    classification: False
    onehot_encode_target: False
    combine_files: False
    percentage_zeros_threshold: 1.0
    correlation_metric: pearson
    input_max_correlation_threshold: 1.0

featurize:
    features:
    add_rolling_features: True
    rolling_window_size: 10
    remove_features:
    target_min_correlation_threshold: 0.0

split:
    train_split: 0.5
    shuffle_files: False
    calibrate_split: 0.0

scale:
    input: minmax
    output:

sequentialize:
    window_size: 10
    overlap: 0
    target_size: 1
    shuffle_samples: False
    future_predict: False

train:
    learning_method: cnn
    n_epochs: 20
    batch_size: 256
    kernel_size: 5
    early_stopping: True
    patience: 10

evaluate:
