profile:
    # dataset: broaching_small
    # dataset: broaching_synchronized
    # dataset: ideko
    dataset: cnc_milling

clean:
    target: S1_OutputVoltage
    # target: Accel_FFT_Acc1_range1_Amplitudes_0
    classification: False
    onehot_encode_target: False
    combine_files: False
    percentage_zeros_threshold: 1.0
    correlation_metric: pearson
    input_max_correlation_threshold: 1.0

featurize:
    # If empty, all input variables are used
    variables_to_include:
        # - Accel_FFT_Acc2_range1_Amplitudes_0
        # - Y1_ActualVelocity
        # - acc1_x
        # - acc1_y
        # - acc1_z

    # By setting this to True, the add_-options below are overrided.
    use_all_engineered_features_on_all_variables: True

    # List the variables below each add_* to add engineered feature
    add_sum:
        # - variable1
    add_gradient:
        # - variable1
    add_mean:
        # - variable1
    add_maximum:
        # - variable1
    add_minimum:
        # - variable1
    add_min_max_range:
        # - variable1
    add_slope:
        # - variable1
    add_slope_sin:
        # - variable1
    add_slope_cos:
        # - variable1
    add_standard_deviation:
        # - efficiency
    add_variance:
        # - variable1
    add_peak_frequency:
        # - variable1
    rolling_window_size_sum: 10
    rolling_window_size_mean: 10
    rolling_window_size_max_min: 10
    rolling_window_size_standard_deviation: 10

    # List features here to remove the raw variables after engineering features
    # from them
    remove_features:
        # - acc1_z
    target_min_correlation_threshold: 0.0

split:
    train_split: 0.5
    shuffle_files: False
    calibrate_split: 0.0

scale:
    input: minmax
    output:

sequentialize:
    window_size: 5
    overlap: 0
    target_size: 1
    shuffle_samples: False
    future_predict: False

train:
    learning_method: dnn
    n_epochs: 100
    batch_size: 256
    kernel_size: 5
    early_stopping: True
    patience: 20

evaluate:
