profile:

featurize:
  raw_subfolder: experiment1
  features:
    - X1_ActualPosition # actual x position of part (mm)
    - X1_ActualVelocity # actual x velocity of part (mm/s)
    - X1_ActualAcceleration # actual x acceleration of part (mm/s/s)
    - X1_CommandPosition # reference x position of part (mm)
    - X1_CommandVelocity # reference x velocity of part (mm/s)
    - X1_CommandAcceleration # reference x acceleration of part (mm/s/s)
    - X1_CurrentFeedback # current (A)
    - X1_DCBusVoltage # voltage (V)
    - X1_OutputCurrent # current (A)
    - X1_OutputVoltage # voltage (V)
    - X1_OutputPower # power (kW)
    - Y1_ActualPosition # actual y position of part (mm)
    - Y1_ActualVelocity # actual y velocity of part (mm/s)
    - Y1_ActualAcceleration # actual y acceleration of part (mm/s/s)
    - Y1_CommandPosition # reference y position of part (mm)
    - Y1_CommandVelocity # reference y velocity of part (mm/s)
    - Y1_CommandAcceleration # reference y acceleration of part (mm/s/s)
    - Y1_CurrentFeedback # current (A)
    - Y1_DCBusVoltage # voltage (V)
    - Y1_OutputCurrent # current (A)
    - Y1_OutputVoltage # voltage (V)
    - Y1_OutputPower # power (kW)
    - Z1_ActualPosition # actual z position of part (mm)
    - Z1_ActualVelocity # actual z velocity of part (mm/s)
    - Z1_ActualAcceleration # actual z acceleration of part (mm/s/s)
    - Z1_CommandPosition # reference z position of part (mm)
    - Z1_CommandVelocity # reference z velocity of part (mm/s)
    - Z1_CommandAcceleration # reference z acceleration of part (mm/s/s)
    - Z1_CurrentFeedback # current (A)
    - Z1_DCBusVoltage # voltage (V)
    - Z1_OutputCurrent # current (A)
    - Z1_OutputVoltage # voltage (V)
    - S1_ActualPosition # actual position of spindle (mm)
    - S1_ActualVelocity # actual velocity of spindle (mm/s)
    - S1_ActualAcceleration # actual acceleration of spindle (mm/s/s)
    - S1_CommandPosition # reference position of spindle (mm)
    - S1_CommandVelocity # reference velocity of spindle (mm/s)
    - S1_CommandAcceleration # reference acceleration of spindle (mm/s/s)
    - S1_CurrentFeedback # current (A)
    - S1_DCBusVoltage # voltage (V)
    - S1_OutputCurrent # current (A)
    - S1_OutputVoltage # voltage (V)
    - S1_OutputPower # current (A)
    - S1_SystemInertia # torque inertia (kg*m^2)
    - M1_CURRENT_PROGRAM_NUMBER # number the program is listed under on the CNC
    - M1_sequence_number # line of G-code being executed
    - M1_CURRENT_FEEDRATE # instantaneous feed rate of spindle
    # - Machining_Process # the current machining stage being performed. Includes preparation, tracing up  and down the "S" curve involving different layers, and repositioning of the spindle as it moves through the air to a certain starting point should not be used as input the the neural network.
  target: X1_ActualPosition

split:
  train_split: 0.5

scale:
  method: standard # choose between standard and minmax

sequentialize:
  # History window sample size
  hist_size: 50
  target_size: 50

train:
  net: cnn
  n_epochs: 20
  batch_size: 128
  kernel_size: 2

evaluate:
