profile:
    dataset: cnc_toolwear
    # dataset: automotive

clean:
    target: X1_CommandPosition
    # target: Axis_X_Real_Position
    # target: PN
    classification: False
    onehot_encode_target: False
    combine_files: False
    percentage_zeros_threshold: 1.0
    correlation_metric: pearson
    input_max_correlation_threshold: 1.0

featurize:
    features:
        # - feature1
        # - feature2
    add_rolling_features: True
    rolling_window_size: 200
    remove_features:
        # - X1_ActualPosition
        # - feature1
        # - feature2
        # - Axis_Y_Position_Diff
        # - Axis_Z_Position_Diff
        # - Axis_B_Position_Diff
        # - Abs_Sum_Position_Diff

    target_min_correlation_threshold: 0.0

split:
    train_split: 0.7
    shuffle_files: False
    calibrate_split: 0.0

scale:
    input: minmax
    output: minmax

sequentialize:
    window_size: 100
    overlap: 50
    target_size: 1
    shuffle_samples: False
    future_predict: False

train:
    train: True
    learning_method: cnn
    n_epochs: 50
    batch_size: 256
    kernel_size: 5
    early_stopping: False
    patience: 10

evaluate:
