clean:
  classification: false
  combine_files: false
  correlation_metric: pearson
  input_max_correlation_threshold: 1.0
  onehot_encode_target: false
  percentage_zeros_threshold: 1.0
  target: Accel_FFT_Acc1_range1_Amplitudes_0
evaluate:
  show_inputs: true
featurize:
  add_gradient: null
  add_maximum: null
  add_mean: null
  add_min_max_range: null
  add_minimum: null
  add_peak_frequency: null
  add_slope: null
  add_slope_cos: null
  add_slope_sin: null
  add_standard_deviation: null
  add_sum: null
  add_variance: null
  remove_features: null
  rolling_window_size_max_min: 10
  rolling_window_size_mean: 10
  rolling_window_size_standard_deviation: 10
  rolling_window_size_sum: 10
  target_min_correlation_threshold: 0.0
  use_all_engineered_features_on_all_variables: false
  variables_to_include: null
profile:
  dataset: ideko
scale:
  input: minmax
  output: null
sequentialize:
  future_predict: false
  overlap: 0
  shuffle_samples: false
  target_size: 1
  window_size: 5
split:
  calibrate_split: 0.0
  shuffle_files: false
  train_split: 0.7
train:
  batch_size: 256
  early_stopping: true
  kernel_size: 5
  learning_method: cnn
  n_epochs: 10
  patience: 20
