profile:
    dataset: broaching_with_toolwear
    # dataset: cnc_milling_with_toolwear

clean:
    # target: fas_category
    # target: Accel_Severity_Acc1_Range1
    # target: S1_OutputPower
    target: tool_wear
    classification: False
    onehot_encode_target: False
    combine_files: False
    percentage_zeros_threshold: 1.0
    correlation_metric: pearson
    input_max_correlation_threshold: 1.0

featurize:
    # If empty, all input variables are used
    variables_to_include:
        - acc1_x
        - acc1_y
        - acc1_z
        - acc2_x
        - acc2_y
        - acc2_z
        # - Accel_Severity_Acc2_Range1
        # - X1_CommandPosition
        # - Y1_CommandPosition
        # - Z1_CommandPosition

    # By setting this to True, the add_-options below are overrided.
    use_all_engineered_features_on_all_variables: True

    # List the variables below each add_* to add engineered feature
    add_sum:
        # - variable1
    add_gradient:
        # - variable1
    add_mean:
        # - variable1
    add_maximum:
        # - variable1
    add_minimum:
        # - variable1
    add_min_max_range:
        # - variable1
    add_slope:
        # - variable1
    add_slope_sin:
        # - variable1
    add_slope_cos:
        # - variable1
    add_standard_deviation:
        # - variable1
    add_variance:
        # - variable1
    add_peak_frequency:
        # - variable1
    rolling_window_size_sum: 128000
    rolling_window_size_mean: 128000
    rolling_window_size_max_min: 128000
    rolling_window_size_standard_deviation: 128000

    # List features here to remove the raw variables after engineering features
    # from them
    remove_features:
        # - variable1
    target_min_correlation_threshold: 0.0

split:
    train_split: 0.7
    shuffle_files: True
    calibrate_split: 0.0

scale:
    input: minmax
    output:

sequentialize:
    window_size: 1
    overlap: 0
    target_size: 1
    shuffle_samples: True
    future_predict: False

train:
    learning_method: xgboost
    n_epochs: 1000
    batch_size: 256
    kernel_size: 128
    early_stopping: True
    patience: 100
    hyperparameter_tuning: False

evaluate:
    show_inputs: False
